/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { models, } from "powerbi-client";
export namespace Components {
    interface WizPowerbi {
        "embedUrl": string;
        "filters": models.IFilter[];
        "idPbi": string;
        "maxMobileSize": number;
        "showFilterBar": boolean;
        "showMenuButton": boolean;
        "token": string;
        "tokenType": models.TokenType;
        "type": string;
    }
}
declare global {
    interface HTMLWizPowerbiElement extends Components.WizPowerbi, HTMLStencilElement {
    }
    var HTMLWizPowerbiElement: {
        prototype: HTMLWizPowerbiElement;
        new (): HTMLWizPowerbiElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-powerbi": HTMLWizPowerbiElement;
    }
}
declare namespace LocalJSX {
    interface WizPowerbi {
        "embedUrl"?: string;
        "filters"?: models.IFilter[];
        "idPbi"?: string;
        "maxMobileSize"?: number;
        "showFilterBar"?: boolean;
        "showMenuButton"?: boolean;
        "token"?: string;
        "tokenType"?: models.TokenType;
        "type"?: string;
    }
    interface IntrinsicElements {
        "wiz-powerbi": WizPowerbi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-powerbi": LocalJSX.WizPowerbi & JSXBase.HTMLAttributes<HTMLWizPowerbiElement>;
        }
    }
}
